import { Component, inject } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, Validators } from '@angular/forms';
import { finalize, forkJoin, of } from 'rxjs';
import { AuthService } from '../../../core/auth/auth.service';
import { PERMISSIONS } from '../../../core/auth/auth.models';
import { AuthorizationService } from '../../../core/auth/authorization.service';
import { FeedbackService } from '../../../core/services/feedback.service';
import { CreateVisitRequest, Visit, VisitStatus } from '../../visits/models/visit.models';
import { VisitsApiService } from '../../visits/services/visits-api.service';
import { AccessApiService, AccessAuthorizationRequestDto, AccessInvitationDto } from '../services/access-api.service';

type AccessTab = 'book' | 'invite' | 'authorizations';

@Component({ selector: 'app-access-page', templateUrl: './access.page.html', styleUrls: ['./access.page.scss'], standalone: false })
export class AccessPage {
  private readonly api = inject(AccessApiService); private readonly visitsApi = inject(VisitsApiService); private readonly formBuilder = inject(FormBuilder); private readonly feedback = inject(FeedbackService); private readonly auth = inject(AuthService); private readonly authorization = inject(AuthorizationService); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router);
  readonly form = this.formBuilder.nonNullable.group({ unitId: ['', Validators.required], visitorName: ['', [Validators.required, Validators.maxLength(150)]], visitorDocument: ['', [Validators.required, Validators.maxLength(50)]], validUntil: [new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().slice(0, 16), Validators.required] });
  readonly visitForm = this.formBuilder.nonNullable.group({ visitorName: ['', [Validators.required, Validators.maxLength(150)]], visitorDocument: ['', [Validators.required, Validators.maxLength(50)]], residentName: ['', [Validators.required, Validators.maxLength(150)]], unitLabel: ['', [Validators.maxLength(80)]], blockLabel: ['', [Validators.maxLength(80)]], visitorPhone: ['', Validators.maxLength(50)], vehiclePlate: ['', Validators.maxLength(20)], observations: ['', Validators.maxLength(500)] });
  readonly qrForm = this.formBuilder.nonNullable.group({ token: ['', Validators.required] });
  readonly requestForm = this.formBuilder.nonNullable.group({ unitId: ['', Validators.required], visitorAlias: ['', [Validators.required, Validators.maxLength(150)]], visitorDocument: ['', [Validators.required, Validators.maxLength(50)]] });
  readonly recurringForm = this.formBuilder.nonNullable.group({ unitId: ['', Validators.required], visitorAlias: ['', Validators.required], validUntil: ['', Validators.required] });
  readonly privacyForm = this.formBuilder.nonNullable.group({ personalHistoryEnabled: true, reusableVisitorProfilesEnabled: false });
  units: Record<string, unknown>[] = []; invitations: AccessInvitationDto[] = []; authorizationRequests: AccessAuthorizationRequestDto[] = []; visits: Visit[] = []; activeTab: AccessTab = 'book'; visitStatus: VisitStatus | '' = ''; visitSearch = ''; loading = false; submitting = false; latestToken = '';
  get canOperate(): boolean { return this.authorization.hasPermission(PERMISSIONS.ACCESS_MANAGE); }
  get canUseAccess(): boolean { return this.authorization.hasAnyPermission([PERMISSIONS.ACCESS_MANAGE, PERMISSIONS.ACCESS_REQUEST]); }
  get canCreateVisits(): boolean { return this.authorization.hasPermission(PERMISSIONS.VISITS_CREATE); }
  get canUpdateVisits(): boolean { return this.authorization.hasPermission(PERMISSIONS.VISITS_UPDATE); }
  get filteredVisits(): Visit[] { const search = this.visitSearch.trim().toLocaleLowerCase(); return this.visits.filter((visit) => (!this.visitStatus || visit.status === this.visitStatus) && (!search || [visit.visitorName, visit.visitorDocument, visit.residentName, visit.unitLabel, visit.blockLabel].filter(Boolean).join(' ').toLocaleLowerCase().includes(search))); }
  get activeVisitsCount(): number { return this.visits.filter((visit) => visit.status === 'INGRESADA').length; }
  get pendingVisitsCount(): number { return this.visits.filter((visit) => visit.status === 'PENDIENTE').length; }
  ionViewWillEnter(): void { const tab = this.route.snapshot.queryParamMap.get('tab'); if (tab === 'book' || tab === 'invite' || tab === 'authorizations') this.activeTab = tab; this.load(); }
  setTab(tab: AccessTab): void { this.activeTab = tab; void this.router.navigate([], { relativeTo: this.route, queryParams: { tab }, queryParamsHandling: 'merge' }); }
  load(): void { this.loading = true; const accessData$ = this.canUseAccess ? forkJoin({ units: this.api.units(), invitations: this.api.invitations(), requests: this.api.authorizationRequests(), privacy: this.api.privacy() }) : of({ units: [] as Record<string, unknown>[], invitations: [] as AccessInvitationDto[], requests: [] as AccessAuthorizationRequestDto[], privacy: {} as Record<string, unknown> }); forkJoin({ visits: this.visitsApi.list(), access: accessData$ }).pipe(finalize(() => this.loading = false)).subscribe({ next: ({ visits, access }) => { this.visits = visits; this.units = access.units; this.invitations = access.invitations; this.authorizationRequests = access.requests; this.privacyForm.patchValue({ personalHistoryEnabled: Boolean(access.privacy['personal_history_enabled']), reusableVisitorProfilesEnabled: Boolean(access.privacy['reusable_visitor_profiles_enabled']) }); }, error: async error => this.feedback.error(this.auth.getErrorMessage(error)) }); }
  createVisit(): void { if (this.visitForm.invalid || this.submitting) { this.visitForm.markAllAsTouched(); return; } this.submitting = true; const raw = this.visitForm.getRawValue(); const payload: CreateVisitRequest = { visitorName: raw.visitorName.trim(), visitorDocument: raw.visitorDocument.trim(), residentName: raw.residentName.trim(), unitLabel: raw.unitLabel.trim() || null, blockLabel: raw.blockLabel.trim() || null, visitorPhone: raw.visitorPhone.trim() || null, vehiclePlate: raw.vehiclePlate.trim() || null, observations: raw.observations.trim() || null, registrationType: 'MANUAL_CONSERJERIA' }; this.visitsApi.create(payload).pipe(finalize(() => this.submitting = false)).subscribe({ next: async () => { this.visitForm.reset(); await this.feedback.success('Visita incorporada al libro. Registra su ingreso cuando cruce recepción.'); this.load(); }, error: async error => this.feedback.error(this.auth.getErrorMessage(error)) }); }
  updateVisitStatus(visit: Visit, status: VisitStatus): void { this.visitsApi.updateStatus(visit.id, { status }).subscribe({ next: async () => { await this.feedback.success(status === 'INGRESADA' ? 'Ingreso registrado en el libro de visitas.' : 'Salida registrada y visita finalizada.'); this.load(); }, error: async error => this.feedback.error(this.auth.getErrorMessage(error)) }); }
  create(): void { if (this.form.invalid || this.submitting) { this.form.markAllAsTouched(); return; } this.submitting = true; const value = this.form.getRawValue(); const validUntil = new Date(Date.now() + 24 * 60 * 60 * 1000); this.api.invite({ unitId: value.unitId, visitorName: value.visitorName.trim(), visitorDocument: value.visitorDocument.trim(), invitationType: 'SINGLE', validFrom: new Date().toISOString(), validUntil: validUntil.toISOString() }).pipe(finalize(() => this.submitting = false)).subscribe({ next: async result => { this.latestToken = String(result['token'] ?? ''); this.form.reset({ unitId: '', visitorName: '', visitorDocument: '', validUntil: validUntil.toISOString().slice(0, 16) }); await this.feedback.success('Invitación creada. Comparte el código QR temporal de forma segura.'); this.load(); }, error: async error => this.feedback.error(this.auth.getErrorMessage(error)) }); }
  registerQr(): void { if (this.qrForm.invalid || this.submitting) { this.qrForm.markAllAsTouched(); return; } this.submitting = true; const token = this.qrForm.controls.token.value.trim(); this.api.tokenEvent(token).pipe(finalize(() => this.submitting = false)).subscribe({ next: async () => { this.qrForm.reset(); await this.feedback.success('Ingreso registrado desde el código temporal.'); this.load(); }, error: async error => this.feedback.error(this.auth.getErrorMessage(error)) }); }
  requestAuthorization(): void { if (this.requestForm.invalid || this.submitting) { this.requestForm.markAllAsTouched(); return; } this.submitting = true; const value = this.requestForm.getRawValue(); this.api.requestAuthorization({ unitId: value.unitId, visitorAlias: value.visitorAlias.trim(), visitorDocument: value.visitorDocument.trim(), validUntil: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString() }).pipe(finalize(() => this.submitting = false)).subscribe({ next: async () => { this.requestForm.reset(); await this.feedback.success('Solicitud enviada al residente. Al aprobarla, la visita se registra en el libro.'); this.load(); }, error: async error => this.feedback.error(this.auth.getErrorMessage(error)) }); }
  decideRequest(request: AccessAuthorizationRequestDto, decision: 'APPROVED' | 'REJECTED'): void { this.api.decideAuthorization(request.id, decision).subscribe({ next: async () => { await this.feedback.success(decision === 'APPROVED' ? 'Acceso autorizado.' : 'Solicitud rechazada.'); this.load(); }, error: async error => this.feedback.error(this.auth.getErrorMessage(error)) }); }
  createRecurring(): void { if (this.recurringForm.invalid) { this.recurringForm.markAllAsTouched(); return; } const value = this.recurringForm.getRawValue(); this.api.recurringRule({ unitId: value.unitId, visitorAlias: value.visitorAlias, daysOfWeek: 'MON,TUE,WED,THU,FRI', startTime: '08:00', endTime: '20:00', validFrom: new Date().toISOString(), validUntil: new Date(value.validUntil).toISOString(), notifyOnEntry: true }).subscribe({ next: async () => { this.recurringForm.reset(); await this.feedback.success('Regla recurrente creada con horario laboral y vencimiento.'); }, error: async error => this.feedback.error(this.auth.getErrorMessage(error)) }); }
  savePrivacy(): void { this.api.savePrivacy(this.privacyForm.getRawValue()).subscribe({ next: async () => this.feedback.success('Preferencias de privacidad actualizadas.'), error: async error => this.feedback.error(this.auth.getErrorMessage(error)) }); }
  event(invitation: AccessInvitationDto, type: string): void { this.api.event(invitation.id, type, 'CONCIERGE_PANEL').subscribe({ next: async () => { await this.feedback.success(type === 'REVOKED' ? 'Autorización revocada.' : 'Evento de acceso registrado.'); this.load(); }, error: async error => this.feedback.error(this.auth.getErrorMessage(error)) }); }
  statusLabel(status: VisitStatus): string { return ({ PENDIENTE: 'Pendiente', INGRESADA: 'En recinto', FINALIZADA: 'Finalizada', CANCELADA: 'Cancelada' })[status]; }
  statusColor(status: VisitStatus): 'warning' | 'primary' | 'success' | 'medium' { return ({ PENDIENTE: 'warning', INGRESADA: 'primary', FINALIZADA: 'success', CANCELADA: 'medium' } as const)[status]; }
}
