// This file is generated by scripts/prepare-env.mjs
// Do not edit manually.
export const generatedEnvironment = {
  apiBaseUrl: "http://localhost:8080/api/v1",
  storagePrefix: "domus",
} as const;
