// This file is generated by scripts/prepare-env.mjs
// Safe local fallback for first install.
export const generatedEnvironment = {
  apiBaseUrl: 'http://localhost:8080/api/v1',
  storagePrefix: 'domus',
} as const;
