import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');
const targetMode = (process.argv[2] ?? process.env.DOMUS_APP_ENV ?? 'development').trim();

const MODE_ALIASES = {
  dev: 'development',
  development: 'development',
  prod: 'production',
  production: 'production',
};

const mode = MODE_ALIASES[targetMode] ?? targetMode;
const envFiles = [
  '.env',
  `.env.${mode}`,
  '.env.local',
  `.env.${mode}.local`,
];

const parsedEnv = envFiles.reduce((accumulator, fileName) => {
  const filePath = path.join(projectRoot, fileName);

  if (!existsSync(filePath)) {
    return accumulator;
  }

  return {
    ...accumulator,
    ...parseDotenv(readFileSync(filePath, 'utf8')),
  };
}, {});

const mergedEnv = {
  ...parsedEnv,
  ...Object.fromEntries(
    Object.entries(process.env).filter(([, value]) => value !== undefined),
  ),
};

const configuredApiBaseUrl = mergedEnv.DOMUS_API_BASE_URL?.trim();

if (!configuredApiBaseUrl && mode === 'production') {
  throw new Error(
    'DOMUS_API_BASE_URL es obligatorio para builds de produccion. Define la variable en tu pipeline o en un archivo .env local no versionado.',
  );
}

const apiBaseUrl = normalizeApiBaseUrl(
  configuredApiBaseUrl ?? 'http://localhost:8080/api/v1',
);

const storagePrefix = (mergedEnv.DOMUS_STORAGE_PREFIX ?? 'domus').trim();

if (!storagePrefix) {
  throw new Error('DOMUS_STORAGE_PREFIX no puede estar vacio.');
}

const generatedFilePath = path.join(projectRoot, 'src', 'environments', 'environment.generated.ts');
const generatedContent = `// This file is generated by scripts/prepare-env.mjs
// Do not edit manually.
export const generatedEnvironment = {
  apiBaseUrl: ${JSON.stringify(apiBaseUrl)},
  storagePrefix: ${JSON.stringify(storagePrefix)},
} as const;
`;

writeFileSync(generatedFilePath, generatedContent, 'utf8');

console.log(
  `[prepare-env] mode=${mode} apiBaseUrl=${apiBaseUrl} storagePrefix=${storagePrefix}`,
);

function parseDotenv(content) {
  return content.split(/\r?\n/).reduce((accumulator, line) => {
    const trimmedLine = line.trim();

    if (!trimmedLine || trimmedLine.startsWith('#')) {
      return accumulator;
    }

    const separatorIndex = trimmedLine.indexOf('=');

    if (separatorIndex === -1) {
      return accumulator;
    }

    const key = trimmedLine.slice(0, separatorIndex).trim();
    const rawValue = trimmedLine.slice(separatorIndex + 1).trim();
    const value = stripWrappingQuotes(rawValue);

    if (!key) {
      return accumulator;
    }

    return {
      ...accumulator,
      [key]: value,
    };
  }, {});
}

function stripWrappingQuotes(value) {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }

  return value;
}

function normalizeApiBaseUrl(value) {
  const normalizedValue = value.trim().replace(/\/+$/, '');

  if (!/^https?:\/\//.test(normalizedValue)) {
    throw new Error(
      `DOMUS_API_BASE_URL debe comenzar con http:// o https://. Valor recibido: ${value}`,
    );
  }

  return normalizedValue;
}
